# Generated by Django 2.0 on 2021-10-19 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeowner', '0004_bookinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeinfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
